# String Comparison
print("=" * 40)
print("STRING COMPARISON".center(40))
print("=" * 40)
# Variables
language_1 = "Python"
language_2 = "Python"
language_3 = "Java"
fruit_1 = "Apple"
fruit_2 = "Banana"
# Display Original Values
print(f"Language 1 : {language_1}")
print(f"Language 2 : {language_2}")
print(f"Language 3 : {language_3}")
print(f"Fruit 1    : {fruit_1}")
print(f"Fruit 2    : {fruit_2}")
print()
# Separator 1 (equal ==)
print("-" * 40)
print("Equal (==)".center(40))
print("-" * 40)
print(f"{language_1} == {language_2} : {language_1 == language_2}")
print(f"{language_1} == {language_3} : {language_1 == language_3}")
print()
# Separator 2 (not equal to ==)
print("-" * 40)
print("Not Equal (!=)".center(40))
print("-" * 40)
print(f"{language_1} != {language_2} : {language_1 != language_2}")
print(f"{language_1} != {language_3} : {language_1 != language_3}")
print()
# Separator 3 (Greater than)
print("-" * 40)
print("Greater Than (>)".center(40))
print("-" * 40)
print(f"{language_1} > {language_2} : {language_1 > language_2}")
print(f"{language_1} > {language_3} : {language_1 > language_3}")
print()
# Separator 4 (Less than)
print("-" * 40)
print("Less Than (<)".center(40))
print("-" * 40)
print(f"{language_1} < {language_2} : {language_1 < language_2}")
print(f"{language_1} < {language_3} : {language_1 < language_3}")
print(f"{fruit_1} < {fruit_2} : {fruit_1 < fruit_2}")
print()
# Separator 5 (Greater than or equal to)
print("-" * 40)
print("Greater Than or Equal (>=)".center(40))
print("-" * 40)
print(f"{language_1} >= {language_3} : {language_1 >= language_3}")
print(f"{fruit_1} >= {fruit_2} : {fruit_1 >= fruit_2}")
print()
# Separator 6 (Less than or equal to)
print("-" * 40)
print("Less Than or Equal (<=)".center(40))
print("-" * 40)
print(f"{language_1} <= {language_3} : {language_1 <= language_3}")
print(f"{fruit_1} <= {fruit_2} : {fruit_1 <= fruit_2}")
print()
# Separator 7 (Case sensitivity)
print("-" * 40)
print("Case Sensitivity".center(40))
print("-" * 40)
print(f'{language_1} == "python" : {language_1 == "python"}')
print(f'{language_2} == "Python" : {language_2 == "Python"}')
print()
print("String Comparison demonstrated successfully!")
print("=" * 40)

