student_name = str(input("Please enter your name:"))
english_marks = int(input("Please enter your english marks:"))
math_marks = int(input("Please enter your math marks:"))
science_marks = int(input("Please enter your science marks:"))

print("-" * 40 )
print("STUDENT MARKS". center(40))
print("-" * 40)
print()
print(f"Student Name  : {student_name}")
print(f"English Marks : {english_marks}")
print(f"Math Marks    : {math_marks}")
print(f"Science Marks : {science_marks}")
print("Keep working hard!")
print("-" * 40)
