name = (input("Please enter your name:"))
age = int(input("Please enter your age:"))
city = (input("Please enter your city:"))
favorite_language = (input("Please enter your favorite language:"))
dream_job = (input("Please enter your dream job:"))
print("=" * 40)
print("PERSONAL PROFILE". center(40))
print("=" * 40)
print(f"Name               : {name}")
print(f"Age                : {age}")
print(f"City               : {city}")
print(f"Favorite Language  : {favorite_language}")
print(f"Dream Job          : {dream_job}")
print()
print("Keep learning. Your future is built one line of code at a time!")
print("=" * 40)
