name = (input("Please enter your name:"))
age = int(input("Please enter your age:"))
city = (input("Please enter your city:"))
favorite_programming_language = (input("Please enter your favorite programming language:"))
print()
print("=" * 40)
print("STUDENT PROFILE". center(40))
print("=" * 40)
print(f"Hello {name}!")
print(f"You are {age} years old.")
print(f"You live in {city}.")
print(f"Your favorite programming language is {favorite_programming_language}.")
print(f"Next year you will be {age + 1}.")
print("Keep learning and keep coding!")
print("=" * 40)