#Case conversion methods
print("-" * 40)
print("CASE CONVERSION METHODS".center(40))
print("-" * 40)
#Variables
name = "Noor"
city = "Peshawar"
quote = "Every expert is once a beginner"
#Display Original Results
print(f"Name          : {name}")
print(f"City          : {city}")
print(f"Quote         : {quote}")
#Separator 1(Upper)
print("-" * 40)
print("UPPER() METHOD".center(40))
print("-" * 40)
print(f"Name          : {name.upper()}")
print(f"City          : {city.upper()}")
print(f"Quote         : {quote.upper()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("Upper() method demonstrated successfully!")
print("-" * 40)
#Separator 2(Lower)
print("-" * 40)
print("LOWER() METHOD".center(40))
print("-" * 40)
print(f"Name          : {name.lower()}")
print(f"City          : {city.lower()}")
print(f"Quote         : {quote.lower()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("Lower() method demonstrated successfully!")
print("-" * 40)
#Separator 3(Title)
print("-" * 40)
print("TITLE() METHOD".center(40))
print("-" * 40)
print(f"Name          : {name.title()}")
print(f"City          : {city.title()}")
print(f"Quote         : {quote.title()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("Title() method demonstrated successfully!")
print("-" * 40)
#Separator 4(Capitalize)
print("-" * 40)
print("CAPITALIZE() METHOD".center(40))
print("-" * 40)
print(f"Name          : {name.capitalize()}")
print(f"City          : {city.capitalize()}")
print(f"Quote         : {quote.capitalize()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("Capitalize() method demonstrated successfully!")
print("-" * 40)
#Separator 5(Swapcase)
print("SWAPCASE() METHOD".center(40))
print("-" * 40)
print(f"Name          : {name.swapcase()}")
print(f"City          : {city.swapcase()}")
print(f"Quote         : {quote.swapcase()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("Swapcase() method demonstrated successfully!")
print("-" * 40) 
print()
print("Case Conversion Methods Demonstrated Successfully!")
print("=" * 40) 

