#Strip methods
print("-" * 40)
print("STRIP METHODS".center(40))
print("-" * 40)
#Variables
name = "Noor  "
city = "  Peshawar"
quote = "   Every expert is once a beginner   "
#Display Original Results
print(f"Name          : {name}")
print(f"City          : {city}")
print(f"Quote         : {quote}")
#Separator 1(strip)
print("-" * 40)
print("strip() Method".center(40))
print("-" * 40)
print(f"Name          : {name.strip()}")
print(f"City          : {city.strip()}")
print(f"Quote         : {quote.strip()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("strip() Method demonstrated successfully!")
print("-" * 40)
#Separator 2(lstrip)
print("lstrip() Method".center(40))
print("-" * 40)
print(f"Name          : {name.lstrip()}")
print(f"City          : {city.lstrip()}")
print(f"Quote         : {quote.lstrip()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print()
print("lstrip() Method demonstrated successfully!")
print("-" * 40)
#Separator 3(rstrip)
print("rstrip() Method".center(40))
print("-" * 40)
print(f"Name          : {name.rstrip()}")
print(f"City          : {city.rstrip()}")
print(f"Quote         : {quote.rstrip()}")
print(f"Original Name : {name}")
print(f"Original City : {city}")
print(f"Original Quote: {quote}")
print("rstrip() Method demonstrated successfully!")
print("-" * 40)
print()
print("STRIP() Methods Demonstrated Successfully!")
print("=" * 40) 


