#Search methods
print("-" * 40)
print("SEARCH METHODS".center(40))
print("-" * 40)
#Variables
language = "Python"
course = "Web Development"
email = "mamoonaa.noor@gmail.com"
#Display Original Results
print(f"Language          : {language}")
print(f"Course            : {course}")
print(f"Email             : {email}")
#Separator 1(find)
print("-" * 40)
print("find() Method".center(40))
print("-" * 40)
print(f"find Language      : {language.find('Pyt')}")
print(f"find Course        : {course.find('Development')}")    
print(f"find @             : {email.find('@')}")
print(f"find Missing       : {course.find('Java')}")
print()
print(f"Language          : {language}")
print(f"Course            : {course}")
print(f"Email             : {email}")
print()
print("find() Method demonstrated successfully!")
print("-" * 40)
#Separator 2(rfind)
print("-" * 40)
print("rfind() Method".center(40))
print("-" * 40)
print(f"rfind Language      : {language.rfind('Pyt')}")
print(f"rfind Course        : {course.rfind('Development')}")    
print(f"rfind @             : {email.rfind('@')}")
print(f"rfind Missing       : {course.rfind('Java')}")
print()
print(f"Language          : {language}")
print(f"Course            : {course}")
print(f"Email             : {email}")
print()
print("rfind() Method demonstrated successfully!")
print("-" * 40)
#Separator 3(index)
print("-" * 40)
print("index() Method".center(40))
print("-" * 40)
print(f"index Language      : {language.index('Pyt')}")
print(f"index Course        : {course.index('Development')}")    
print(f"index @             : {email.index('@')}")
print()
print(f"Language          : {language}")
print(f"Course            : {course}")
print(f"Email             : {email}")
print()
print("index() Method demonstrated successfully!")
print("-" * 40)
#Separator 4(rindex)
print("-" * 40)
print("rindex() Method".center(40))
print("-" * 40)
print(f"rindex Language      : {language.rindex('Pyt')}")
print(f"rindex Course        : {course.rindex('Development')}")    
print(f"rindex @             : {email.rindex('@')}")
print()
print(f"Language          : {language}")
print(f"Course            : {course}")
print(f"Email             : {email}")
print()
print("rindex() Method demonstrated successfully!")
print("-" * 40)
#Separator 5(count)
print("-" * 40)
print("count() Method".center(40))
print("-" * 40)
print(f"count Language      : {language.count('P')}")
print(f"count Course        : {course.count('e')}")    
print(f"count @             : {email.count('@')}")
print(f"count Missing       : {course.count('Java')}")
print()
print(f"Language          : {language}")
print(f"Course            : {course}")
print(f"Email             : {email}")
print()
print("count() Method demonstrated successfully!")
print("-" * 40)


